#version 450

layout(binding = 0) uniform UniformBufferObject {
    int width;
    int height;
}
ubo;

layout(std430, binding = 1) buffer src_in { int src[]; };
layout(std430, binding = 2) buffer dst_out { int dst; };

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

shared int wgCounter;

void main() {
    if (gl_LocalInvocationIndex == 0u) wgCounter = int(0);
    barrier(); // synchronize shared memory initialization
    
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    const int row = gid.y;
    const int col = gid.x;
    if (row >= ubo.height || col >= ubo.width) return;

    int val = src[row * ubo.width + col];
    atomicAdd(wgCounter, val);
    barrier();

    // One lane publishes to global
    if (gl_LocalInvocationIndex == 0u) {
        atomicAdd(dst, wgCounter);
    }
}