add_subdirectory(external)
add_subdirectory(vulkan)
add_subdirectory(opengl)
add_subdirectory(opencl)
if (APPLE)
    add_subdirectory(metal)
endif()
add_subdirectory(mat)
add_subdirectory(timer)
if (ENABLE_TRACE)
  message(STATUS "Tracing is enabled")
  add_subdirectory(trace)
endif()
add_subdirectory(threadpool)
add_subdirectory(tests)
add_subdirectory(examples)