name: Core CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # -------------------------
      # Install base tools
      # -------------------------
      - name: Install dependencies
        run: |
          brew update
          brew install cmake ninja molten-vk shaderc

      # -------------------------
      # Set Vulkan environment
      # -------------------------
      - name: Set Vulkan env
        run: |
          echo "VULKAN_SDK=$(brew --prefix molten-vk)" >> $GITHUB_ENV
          echo "$(brew --prefix molten-vk)/bin" >> $GITHUB_PATH
          echo "DYLD_LIBRARY_PATH=$(brew --prefix molten-vk)/lib" >> $GITHUB_ENV
          VULKAN_PREFIX=$(brew --prefix molten-vk)
          echo "VULKAN_PREFIX=$VULKAN_PREFIX" >> $GITHUB_ENV
          echo "Vulkan_INCLUDE_DIR=$VULKAN_PREFIX/include" >> $GITHUB_ENV
          echo "Vulkan_LIBRARY=$VULKAN_PREFIX/lib/libvulkan.dylib" >> $GITHUB_ENV

      # -------------------------
      # Verify Vulkan tools
      # -------------------------
      - name: Check Vulkan tools
        run: |
          echo "VULKAN_SDK=$VULKAN_SDK"
          which glslc || true
          glslc --version || true

      # -------------------------
      # Android SDK + NDK
      # -------------------------
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          sdkmanager "ndk;26.1.10909125"

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      # -------------------------
      # Environment setup
      # -------------------------
      - name: Set environment variables
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/26.1.10909125" >> $GITHUB_ENV

      - name: Build
        run: ./scripts/run.sh